---

- name: Use git to clone ansible repo
  hosts: ubuntu
  become: yes

  tasks:
    - name: install git
      apt:
        name: git
        state: latest

    - name: Use git to clone ansible repo
      git:
        repo: https://github.com/ansible/ansible.git
        dest: /opt
