- name: Install httpd
  hosts: ubuntu
  become: yes

  tasks:
    - name: Apache install
      apt:
        name: apache2
        state: present

    - name: Service management
      service:
       name: apache2
       state: started
       enabled: yes
