---
- hosts: squid
  become: yes
  tasks:
  - name: Add Firewall rules by service
    firewalld:
      zone: public
      service: "{{ item }}"
      permanent: yes
      immediate: yes
      state: enabled
    loop:
      - http
      - https
      - squid
  - name: Add Firewall fule by port number
    firewalld:
      port: 8080-8084/tcp
      permanent: yes
      immediate: yes
      state: disabled
  - name: Rich-rule example
    firewalld:
      rich_rule: rule family=ipv4 forward-port port=443 protocol=tcp to-port=8443
      permanent: yes
      immediate: yes
      state: disabled
