---
- hosts: squid
  become: yes
  vars:
    content_dir: /webhome
    http_port: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          32393235643439323764633933386239396234616261366463326635336634303830353338356435
          3164666134316431666164336532383062323236613766630a366665613638313637636433343837
          63353934613265663339356239663264383636303962313639336130336630666335393862396539
          6635643439373436320a376138313531643162373137613438663762303361303562646439646432
          3939
  # Above generate with: ansible-vault encrypt_string --ask-vault-pass '8080' --name 'http_port'
    admin: webuser
  tasks:
    - name: Push httpd.conf template
      template:
        src: /home/ansible/Ansible/templates/httpd.conf.j2
        dest: /etc/httpd/conf/httpd.conf
        backup: yes
      notify: "restart apache"
    - name: Push index.html template
      template:
        src: /home/ansible/Ansible/templates/index.html.j2
        dest: /webhome/index.html
    - name: Open port 8080 in Firewall
      firewalld:
        zone: public
        port: 8080/tcp
        permanent: yes
        immediate: yes
        state: enabled
    - name: SELinux - Enable HTTPD CGI boolean
      seboolean:
        name: httpd_enable_cgi
        state: yes
        persistent: yes
    - name: SELinux - set secontext
      sefcontext:
        target: '/webhome(/.*)?'
        setype: httpd_sys_content_t
        state: present
    - name: SELinux - Run restorecon
      command: restorecon -irv /webhome
  handlers:
    - name: Restart httpd service
      service:
        name: httpd
        state: restarted
      listen: "restart apache"
