---
- hosts: centosb
  become: yes
  gather_facts: no
  tasks:
    - name: Remove GROUPS
      group:
        name: "{{ item }}"
        state: absent
      loop:
        - college
        - northcampus
    - name: Remove Fred user
      user:
        name: fred
        comment: Fred Smith
        shell: /bin/bash
        groups: college,northcampus
        append: yes
        state: absent
        remove: yes
    - name: Remove Mary user
      user:
        name: mary
        comment: Mary West
        uid: 1234
        groups: college,northcampus
        append: yes
        state: absent
        remove: yes
    - name: Remove Alex user
      user:
        name: alex
        comment: Alex Field
        uid: 1235
        groups: college,northcampus
        append: yes
        state: absent
        remove: yes
