---
# Run with --vault-password-file <path to password file>
- hosts: squid
  become: yes
  vars_files:
    /home/ansible/Ansible/vars/users_Encrypted.yml
  tasks:
    - name: Remove Users
      user:
        name: "{{ item }}"
        state: absent
        remove: yes
      loop: "{{ [learners,college]|flatten(1) }}"
