---
# Run with --ask-vault-pass
- hosts: squid
  become: yes
  vars_files:
    /home/ansible/Ansible/vars/users_Encrypted.yml
  tasks:
    - name: Create Users
      user:
        name: "{{ item }}"
        state: present
      with_items:
        - "{{ learners }}"
        - "{{ college }}"
