---
- hosts: centos
  become: yes
  tasks:
    - name: Copy File
      copy:
        src: /home/ansible/Ansible/files/index.html
        dest: /var/www/html/index.html
      when: ansible_hostname == "centosa"
